---

version: "3"

services:
  example-basic:
    container_name: bench-example-basic
    build: .
    ports:
      - 5173:5173
    command: "sh -c 'npm install ; npm run dev'"
    volumes:
      - ../../:/srv/app
